### ISSUE TITLE
stability issue with esp32-cam.

### ISSUE THREAD

**Issue by Pratiksha0102** [stm32duino/VL53L3CX#11]
Hello!

I am getting trouble While getting range from the sensor using esp32-cam. It works fine for while but after sometime it gives status error 255 and 12 and the problem is that the device is placed at one place and detecting same object but after sometimes it stops detecting the same object and give status code 255 and 12. I don't understand the behavior of the sensor. Is there any hardware issue or library issue?  I am using esp32-cam and vl53l3cx Time of flight sensor.

![Screenshot from 2022-05-16 11-17-10](https://user-images.githubusercontent.com/99065005/168527466-c672b07b-957b-47e8-90fe-aa9e0c96a6c7.png)
![Screenshot from 2022-05-16 11-17-35](https://user-images.githubusercontent.com/99065005/168527483-88c7989f-f863-485b-9d7d-393bad14832a.png)

**Comment by cparata** [comment]
Hello @Pratiksha0102 ,
it's difficult to debug because it depends on your hardware setup. When you get a range status different from 0, it means that the object is not clearly seen by the sensor and the range measurement could be not reliable. Maybe it could be an hardware issue on the sensor, if it works for a while and then it stops to work properly.
I have never seen this issue on my side, but I have never tested the library with ESP32 platforms. I always used STM32 boards.
Best Regards,
Carlo

**Comment by Pratiksha0102** [comment]
Hello! @cparata,  
Thanks for quick response. We moved with vl53l1cx and it works quite well with esp32 platform.
Thanks & Regards,
Pratiksha.
