### ISSUE TITLE
Is there any demo with peoplecouter used by VL53L3CX 

### ISSUE THREAD

**Issue by iot-lorawan** [stm32duino/VL53L3CX#5]
Hi,
  Is there any demo with peoplecouter used by VL53L3CX

**Comment by cparata** [comment]
Hi @iot-lorawan ,
not yet. Do you know a reference library for that?
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @iot-lorawan ,
I got more information from ST Imaging experts. Unfortunately, the people counting demo that you can find [here](https://www.st.com/en/embedded-software/stsw-img010.html) is currently available only for VL53L1X component. So we can implement an Arduino sketch that implements the people counting demo only for the [VL53L1X](https://github.com/stm32duino/VL53L1X) component and the relative expansion board ([X-NUCLEO-VL53L1A1](https://github.com/stm32duino/X-NUCLEO-53L1A1)). Instead, it is not applicable at the moment for VL53L3CX and VL53L1 components. So I have to close this ticket because it is not applicable. If you are interested to have the people counting example for VL53L1X, please, open an issue for this library or the X-NUCLEO-VL53L1A1 library.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @iot-lorawan ,
just for your information, I updated the VL53L1X and the X-NUCLEO-VL53L1A1 libraries adding the people counting demo. If you download the last version of these 2 libraries you can get it.
Best Regards,
Carlo

**Comment by iot-lorawan** [comment]
Hi，
    Thank you very much. the link https://www.st.com/en/embedded-software/stsw-img010.html is very useful for me.

Best Regards
